package com.hushkeyboard

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Phase 4 learned-words dictionary: the THIN Android Keystore + AES-256-GCM
 * wrapper (a deliberate design decision). This is the only piece that touches
 * the device-specific AndroidKeyStore, so per Gate 8 Option 1 it is kept as small
 * as possible and is verified on-device by an instrumented test
 * (`LearnedWordsCipherDeviceTest`) rather than plain JUnit. All the format logic
 * it relies on ([LearnedWordsCodec]) is pure and unit-tested separately.
 *
 * What it does, and only this:
 *   - [encrypt]: AES-256-GCM the plaintext under a hardware-backed key, returning
 *     the documented envelope `[12-byte IV][ciphertext][16-byte tag]`.
 *   - [decrypt]: reverse it.
 *   - [deleteKey]: drop the key (used by the store's disposable-cache recovery).
 *
 * Security properties (SECURITY.md rule 5):
 *   - The AES-256 key is generated INSIDE the AndroidKeyStore and is
 *     **non-exportable** — it never leaves the device's secure hardware (TEE /
 *     StrongBox where available). We only ever hand the key handle to the cipher.
 *   - `setRandomizedEncryptionRequired(true)` forces the system to generate a
 *     FRESH random IV for every encryption — we never reuse or supply an IV. This
 *     is the "fresh random IV per write" guarantee; IV reuse is the classic
 *     GCM foot-gun and the platform prevents it for us here.
 *   - No network, no permission, no dependency: `java.security.KeyStore` and
 *     `javax.crypto.Cipher` are platform APIs.
 *
 * It throws on any failure (bad tag, key invalidated, truncated envelope). Callers
 * (the store) catch those and rebuild — the dictionary is a disposable cache.
 */
class LearnedWordsCipher {

    /**
     * Encrypt [plaintext] and return the on-disk envelope. The IV is generated by
     * the platform (randomized-encryption), read back from the cipher, and packed
     * in front of the ciphertext+tag by [LearnedWordsCodec.packEnvelope].
     */
    fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val body = cipher.doFinal(plaintext) // ciphertext with the 16-byte GCM tag appended
        return LearnedWordsCodec.packEnvelope(cipher.iv, body)
    }

    /**
     * Decrypt an envelope produced by [encrypt]. Splits the IV off the front and
     * authenticates the ciphertext+tag. Throws (e.g. `AEADBadTagException`,
     * `KeyPermanentlyInvalidatedException`) if the data was tampered with, the key
     * changed, or the envelope is malformed — all of which the store treats as
     * "discard and rebuild".
     */
    fun decrypt(envelope: ByteArray): ByteArray {
        val iv = LearnedWordsCodec.envelopeIv(envelope)
        val body = LearnedWordsCodec.envelopeBody(envelope)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(LearnedWordsCodec.GCM_TAG_LENGTH_BYTES * 8, iv)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), spec)
        return cipher.doFinal(body)
    }

    /**
     * Delete the dictionary key from the Keystore. Called by the store when a
     * decrypt fails (the existing key can no longer read its only file, so it has
     * no further value) — the next [encrypt] then transparently generates a new
     * key. Safe to call when no key exists.
     */
    fun deleteKey() {
        val ks = androidKeyStore()
        if (ks.containsAlias(KEY_ALIAS)) ks.deleteEntry(KEY_ALIAS)
    }

    private fun getOrCreateKey(): SecretKey {
        val ks = androidKeyStore()
        (ks.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .setRandomizedEncryptionRequired(true) // fresh random IV every encryption
            .build()
        generator.init(spec)
        return generator.generateKey()
    }

    private fun androidKeyStore(): KeyStore =
        KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "hushkeyboard_learned_words_key"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
    }
}
